#!/bin/sh

# This script needs to be customised FOR EACH NODE,
# since there needs to be IP addresses specific to each node.
# Contrariwise, the NET part should stay the same for all nodes.


PATH=$PATH:/opt/freeha/bin:/opt/freeha/bin/service_scripts

export PATH


IP1="-a 10.1.1.10"
IP2="-b 10.1.2.10"
#IP3="-c 10.1.3.10"

NET1="-A 10.1.1.255"
NET2="-B 10.1.2.255"
#NET3="-C 10.1.3.255"

#Use this if you have more than 2 nodes.
#NODES="-n 3"

case $1 in
	start)
		freehad $NODES $IP1 $NET1 $IP2 $NET2 $IP3 $NET3 </dev/null >/dev/null 2>&1 &
	;;
	stop)
		pkill freehad
	;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
	;;
esac

